/* Automatically generated by '/build/entry.js */

import ZmAside from './packages/Aside';
import ZmContainer from './packages/Container';
import ZmFooter from './packages/Footer';
import ZmForm from './packages/Form';
import ZmFormItem from './packages/FormItem';
import ZmHeader from './packages/Header';
import ZmInput from './packages/Input';
import ZmMain from './packages/Main';
import ZmMenu from './packages/Menu';
import ZmMenuItem from './packages/MenuItem';
import ZmPagination from './packages/Pagination';
import ZmScrollView from './packages/ScrollView';
import ZmSubMenu from './packages/SubMenu';
import ZmSwitch from './packages/Switch';

const components = [
  ZmAside,
  ZmContainer,
  ZmFooter,
  ZmForm,
  ZmFormItem,
  ZmHeader,
  ZmInput,
  ZmMain,
  ZmMenu,
  ZmMenuItem,
  ZmPagination,
  ZmScrollView,
  ZmSubMenu,
  ZmSwitch,
];

const install = (app) => {
  components.forEach((component) => {
    app.component(component.name, component);
  });
};

export default {
  install,
  ...components,
};
